# The URL the site will be built for
base_url = "https://blog.lamps-dev.dev"

content_dir = "content"

title = "Lamp's Blog"
description = "Lamp's Own Blog For News"

default_language = "en"

theme = "apollo"
taxonomies = [{ name = "tags" }]

output_dir = "public"

preserve_dotfiles_in_output = false

compile_sass = false

minify_html = false

generate_feeds = false

feed_filenames = ["atom.xml"]

hard_link_static = false

author = "Lamp"

generate_sitemap = true

generate_robots_txt = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

highlight_theme = "base16-ocean-dark"

render_emoji = false

external_links_target_blank = false

smart_punctuation = false

bottom_footnotes = false

lazy_async_image = false

[slugify]
paths_keep_dates = false

[search]
include_title = true
include_description = false
include_date = true
include_path = false
include_content = true

index_format = "elasticlunr_javascript"

[extra]
blog_section = "posts"


theme = "toggle"
socials = [
  { name = "twitter", url = "https://twitter.com/lampytofficial", icon = "twitter" },
  { name = "github", url = "https://github.com/lamps-dev", icon = "github" },
  { name = "youtube", url = "https://youtube.com/@ilovelampadaire", icon = "youtube" },
]
menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
    { name = "/tags", url = "/tags", weight = 4 },
]
# See this for more options: https://github.com/not-matthias/apollo/blob/main/config.toml#L14
