# The URL the site will be built for
base_url = "https://blog.lamps-dev.dev"

# Site title and description
title = "Lamp's Blog"
description = "Lamp's Own Blog For News"

# Default language
default_language = "en"

# Theme
theme = "apollo"

# Taxonomies
taxonomies = [
    {name = "tags", feed = true},
]

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
highlight_code = true
highlight_theme = "base16-ocean-dark"

[slugify]
paths_keep_dates = false

[search]
include_title = true
include_description = false
include_date = true
include_path = false
include_content = true
index_format = "elasticlunr_javascript"

[extra]
# Put all your custom variables here
author = "Lamp"
github = "lamps-dev"
twitter = "lampytofficial"
youtube = "ilovelampadaire"

# Menu items
menu_items = [
    { name = "Blog", url = "$BASE_URL" },
    { name = "Tags", url = "$BASE_URL/tags" },
    { name = "Archive", url = "$BASE_URL/archive" },
    { name = "About", url = "$BASE_URL/about" },
]

# Theme options
theme_color = "auto" # light, dark, auto

content_dir = "content"

output_dir = "public"

preserve_dotfiles_in_output = false

compile_sass = false

minify_html = false

generate_feeds = false

feed_filenames = ["atom.xml"]

hard_link_static = false

generate_sitemap = true

generate_robots_txt = true


[markdown]
render_emoji = false
external_links_target_blank = false
smart_punctuation = false
bottom_footnotes = false
lazy_async_image = false

